version: '3.9'

services:
  web:
    image: nginx:1.25.3-alpine
    ports:
      - '5120:80'
    volumes:
      - ./web:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      php-fpm:
        condition: service_healthy

  php-fpm:
    image: php:8.2-fpm-alpine
    volumes:
      - ./web:/var/www/html
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:8.1
    ports:
      - '5121:80'
    environment:
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
